### ISSUE TITLE
sdcardfs support

### ISSUE THREAD

**Issue by CamperSamu** [DerpFest-Devices/kernel_oneplus_sm8150#1]
Hi and thanks for working on this awesome ROM.

Is it possible to add support for sdcardfs to fix incompatibly with Common Data when dual booting?

**Comment by NurKeinNeid** [comment]
Well, support is already there. Maybe you mean to remove it instead?

See:
https://github.com/DerpFest-Devices/kernel_oneplus_sm8150/tree/11/fs/sdcardfs

**Comment by CamperSamu** [comment]
Ok so something weirder is going on...
When I use the default Derpfest kernel CommonData won't work, but when I try any other kernel it magically works...
I need to investigate this more then.

**Comment by NurKeinNeid** [comment]
Do you build yourself or do you flash? If the latter, which device?
Guacamole uses different defconfig for example.

You can see here:
https://github.com/DerpFest-Devices/kernel_oneplus_sm8150/commit/0691ad928320e3d6aa4162f928600ea8022b0d2f
